camunda.client.mode=saas
camunda.client.auth.client-id=vyv6KSMN~y_Te2G4HR10fcaiAj_erNdb
camunda.client.auth.client-secret=6DfZ-Zut6IxA12T5E866I4gEwyHJ1JfQjN2uoe~DUfy9Pa3Kw8hp-QNAI3l0kX2X
camunda.client.cloud.cluster-id=a2e4150b-8414-4d10-8c15-99d71d8f42d4
camunda.client.cloud.region=syd-1